export const ActionTypes = {
  SIGN_UP: "SIGN_UP",
  LOGIN: "LOGIN",
  SET_TODOS_NULL: "SET_TODOS_NULL",
  ADD_TODO: "ADD_TODO",
  GET_TODO: "GET_TODO",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_USER_NULL: "SET_USER_NULL",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
